/* eslint-disable */
// This file is generated by TanStack Router. It is included as a bootstrap placeholder.
import { Route as rootRoute } from './routes/__root';
import { Route as indexRoute } from './routes/index';
import { Route as rpcRoute } from './routes/api/rpc/$';

const indexRouteWithChildren = indexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const rpcRouteWithChildren = rpcRoute.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRoute,
} as any);

export const routeTree = rootRoute
  ._addFileChildren({
    indexRoute: indexRouteWithChildren,
    rpcRoute: rpcRouteWithChildren,
  })
  ._addFileTypes() as any;

