{
  "name": "{{PACKAGE_NAME}}",
  "type": "module",
  "private": true,
  "scripts": {
    "dev": "bunx --bun vite dev",
    "build": "bunx --bun vite build",
    "start": "bun run server.ts",
    "type-check": "tsc --noEmit --skipLibCheck",
    "lint": "bunx --bun oxlint src",
    "format": "oxfmt --write src",
    "format:check": "oxfmt --check src",
    "shadcn": "bunx --bun shadcn",
    "drizzle": "bunx --bun drizzle-kit",
    "drizzle:generate": "bun drizzle generate",
    "drizzle:migrate": "bun run migrate.ts",
    "test": "bun test"
  },
  "dependencies": {
    "@base-ui/react": "latest",
    "@better-auth/core": "latest",
    "@better-auth/passkey": "latest",
    "@casl/ability": "latest",
    "@casl/react": "latest",
    "@electric-sql/pglite": "latest",
    "@modelcontextprotocol/sdk": "latest",
    "@orpc/client": "latest",
    "@orpc/react-query": "latest",
    "@orpc/server": "latest",
    "@orpc/zod": "latest",
    "@react-email/components": "latest",
    "@react-email/render": "latest",
    "@sendgrid/mail": "latest",
    "@tailwindcss/vite": "latest",
    "@tanstack/react-form": "latest",
    "@tanstack/react-query": "latest",
    "@tanstack/react-router": "latest",
    "@tanstack/react-router-with-query": "latest",
    "@tanstack/react-start": "latest",
    "better-auth": "latest",
    "class-variance-authority": "latest",
    "clsx": "latest",
    "drizzle-orm": "latest",
    "drizzle-zod": "latest",
    "lucide-react": "latest",
    "pg": "latest",
    "pino": "latest",
    "pino-pretty": "latest",
    "react": "latest",
    "react-dom": "latest",
    "shadcn": "latest",
    "sonner": "latest",
    "tailwind-merge": "latest",
    "tailwindcss": "latest",
    "vite": "latest",
    "zod": "latest"
  },
  "devDependencies": {
    "@types/bun": "latest",
    "@types/pg": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@vitejs/plugin-react-swc": "latest",
    "drizzle-kit": "latest",
    "oxfmt": "latest",
    "oxlint": "latest",
    "typescript": "latest"
  }
}

