BETTER_AUTH_SECRET=
BASE_URL={{BASE_URL}}
TRUSTED_ORIGINS={{BASE_URL}}
DATABASE_URL=
SENDGRID_API_KEY=
FROM_EMAIL=noreply@example.com
APP_NAME={{APP_NAME}}
APP_LOGO_URL=
PRETTY_LOGGING=true
DATABASE_DEBUG=false
PORT=3000

